"""
prosody-filer: XEP-0363 HTTP File Upload service with Hetzner Storage Box (WebDAV) backend.

Implements the server-side of mod_http_upload_external's HMAC token protocol (v1):
  HMAC-SHA256(secret, "{random}/{filename} {filesize}") == query param ?v=

PUT /{random}/{filename}?v={hmac}  -> validate token, upload to Storage Box via WebDAV PUT
GET /{random}/{filename}           -> proxy download from Storage Box via WebDAV GET
"""

from collections.abc import Callable
from dataclasses import dataclass
import hashlib
import hmac
import logging
import os
from typing import Any

import httpx
from fastapi import FastAPI, HTTPException, Path, Query, Request
from fastapi.responses import Response

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("prosody-filer")


@dataclass(frozen=True)
class Settings:
    filer_secret: str
    storage_box_url: str
    storage_box_user: str
    storage_box_pass: str
    max_size: int


def _read_secret(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        value = handle.read().strip()
    if not value:
        raise ValueError(f"secret file is empty: {path}")
    return value


def load_settings_from_env() -> Settings:
    settings = Settings(
        filer_secret=_read_secret(os.environ["FILER_SECRET_FILE"]),
        storage_box_url=os.environ["STORAGE_BOX_URL"].rstrip("/"),
        storage_box_user=os.environ["STORAGE_BOX_USER"],
        storage_box_pass=_read_secret(os.environ["STORAGE_BOX_PASSWORD_FILE"]),
        max_size=int(os.environ.get("UPLOAD_MAX_BYTES", str(20 * 1024 * 1024))),
    )
    logger.info(
        "Configuration loaded: storage_box_url=%s storage_box_user=%s max_size=%d bytes",
        settings.storage_box_url,
        settings.storage_box_user,
        settings.max_size,
    )
    return settings


def _verify_token(secret: str, random: str, filename: str, filesize: int, token: str) -> bool:
    """Validate HMAC-SHA256 token as generated by mod_http_upload_external (v1 protocol)."""
    message = f"{random}/{filename} {filesize}".encode()
    expected = hmac.new(secret.encode(), message, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, token)


def _default_http_client_factory() -> httpx.AsyncClient:
    return httpx.AsyncClient()


def create_app(
    settings: Settings | None = None,
    http_client_factory: Callable[[], Any] | None = None,
) -> FastAPI:
    app = FastAPI()
    app.state.settings = settings or load_settings_from_env()
    app.state.http_client_factory = http_client_factory or _default_http_client_factory

    @app.get("/health")
    async def health() -> dict[str, str]:
        s = app.state.settings
        url = s.storage_box_url + "/"
        try:
            async with app.state.http_client_factory() as client:
                resp = await client.request(
                    "PROPFIND",
                    url,
                    headers={"Depth": "0"},
                    auth=(s.storage_box_user, s.storage_box_pass),
                )
            if resp.status_code not in (200, 207):
                logger.error(
                    "Storage Box health check failed: PROPFIND %s returned HTTP %d\n%s",
                    url,
                    resp.status_code,
                    resp.text[:500],
                )
                raise RuntimeError(f"unexpected status {resp.status_code}")
        except HTTPException:
            raise
        except Exception as exc:
            logger.exception("Storage Box health check failed: PROPFIND %s — %s", url, exc)
            raise HTTPException(status_code=503, detail="Storage Box unavailable") from exc
        logger.debug("Storage Box health check OK: PROPFIND %s returned HTTP %d", url, resp.status_code)
        return {"status": "ok"}

    @app.put("/{random}/{filename}")
    async def upload(
        request: Request,
        random: str = Path(...),
        filename: str = Path(...),
        v: str = Query(..., description="HMAC token from Prosody"),
    ) -> dict[str, str]:
        s = request.app.state.settings
        content_length = int(request.headers.get("content-length", 0))
        if content_length > s.max_size:
            raise HTTPException(status_code=400, detail="File too large")
        if not _verify_token(s.filer_secret, random, filename, content_length, v):
            raise HTTPException(status_code=403, detail="Invalid token")

        body = await request.body()
        content_type = request.headers.get("content-type", "application/octet-stream")

        async with request.app.state.http_client_factory() as client:
            resp = await client.put(
                f"{s.storage_box_url}/{random}/{filename}",
                content=body,
                headers={"Content-Type": content_type},
                auth=(s.storage_box_user, s.storage_box_pass),
            )
        if resp.status_code not in (200, 201, 204):
            logger.error(
                "Storage Box upload failed: PUT %s/%s/%s returned HTTP %d",
                s.storage_box_url, random, filename, resp.status_code,
            )
            raise HTTPException(status_code=502, detail="Storage Box upload failed")
        logger.info("Uploaded: %s/%s (%d bytes)", random, filename, content_length)
        return {"status": "ok"}

    @app.get("/{random}/{filename}")
    async def download(
        request: Request, random: str = Path(...), filename: str = Path(...)
    ) -> Response:
        """Proxy download from Storage Box. No public access to the box required."""
        s = request.app.state.settings
        async with request.app.state.http_client_factory() as client:
            resp = await client.get(
                f"{s.storage_box_url}/{random}/{filename}",
                auth=(s.storage_box_user, s.storage_box_pass),
            )
        if resp.status_code == 404:
            raise HTTPException(status_code=404, detail="Not found")
        if resp.status_code != 200:
            logger.error(
                "Storage Box download failed: GET %s/%s/%s returned HTTP %d",
                s.storage_box_url, random, filename, resp.status_code,
            )
            raise HTTPException(status_code=502, detail="Storage Box unavailable")
        return Response(
            content=resp.content,
            media_type=resp.headers.get("content-type", "application/octet-stream"),
        )

    return app


app = create_app()
